CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME TEXT
);

CREATE TABLE EMPLOYEES (
    EMP_ID INT PRIMARY KEY,
    FULL_NAME TEXT,
    GENDER TEXT,
    DEPT_ID INT,
    SALARY DECIMAL(10,2),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);

INSERT INTO DEPARTMENTS VALUES
(1, 'HR'),
(2, 'IT'),
(3, 'FINANCE'),
(4, 'MARKETING');

INSERT INTO EMPLOYEES VALUES
(101, 'JOHN SMITH', 'MALE', 1, 75000),
(102, 'EMMA JOHNSON', 'FEMALE', 2, 68000),
(103, 'LIAM BROWN', 'MALE', 3, 72000),
(104, 'OLIVIA DAVIS', 'FEMALE', 4, 55000),
(105, 'NOAH WILSON', 'MALE', 2, 64000);

SELECT 
    EMPLOYEES.EMP_ID,
    EMPLOYEES.FULL_NAME,
    EMPLOYEES.GENDER,
    DEPARTMENTS.DEPT_NAME,
    EMPLOYEES.SALARY
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID = DEPARTMENTS.DEPT_ID;

SELECT 
    EMPLOYEES.FULL_NAME,
    DEPARTMENTS.DEPT_NAME,
    EMPLOYEES.SALARY
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID = DEPARTMENTS.DEPT_ID
ORDER BY EMPLOYEES.SALARY DESC;

SELECT 
    EMPLOYEES.FULL_NAME,
    DEPARTMENTS.DEPT_NAME,
    EMPLOYEES.SALARY
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID = DEPARTMENTS.DEPT_ID
WHERE DEPARTMENTS.DEPT_NAME = 'IT';

SELECT 
    EMPLOYEES.FULL_NAME,
    DEPARTMENTS.DEPT_NAME,
    EMPLOYEES.SALARY
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID = DEPARTMENTS.DEPT_ID
WHERE EMPLOYEES.SALARY > 65000;