-- SALESMAN
CREATE TABLE IF NOT EXISTS SALESMAN(
    SALESMAN_ID TEXT PRIMARY KEY,
    SALESMAN_NAME TEXT,
    CITY TEXT,
    COMISSION TEXT
);


INSERT INTO SALESMAN(SALESMAN_ID, SALESMAN_NAME, CITY, COMISSION)
VALUES
("5001","Enrico Andhika","Jakarta","0.15"),
("5002","Nail Knite","Paris","0.13"),
("5005","Pit Alex","London","0.11"),
("5006","Mc Lyon","Paris","0.14"),
("5007","Paul Adam","Rome","0.13"),
("5003","Lauson Hen","San Jose","0.12");


-- CUSTOMER
CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID TEXT,
    CUSTOMER_NAME TEXT PRIMARY KEY,
    CITY TEXT,
    GRADE TEXT,
    SALESMAN_ID TEXT
);


INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, CITY, GRADE, SALESMAN_ID)
VALUES
("3002","bienve jubilo","jakarta","100","5001"),
("3007","brad davis","new york","200","5001"),
("3005","graham zusi","california","200","5002"),
("3008","julian green","london","300","5002"),
("3004","fabian johnson","paris","300","5006"),
("3009","geoff cameron","berlin","100","5003"),
("3003","jozy altidor","moscow","200","5007"),
("3001","brad guzan","london","","5005");


-- ORDERS
CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_NO TEXT PRIMARY KEY,
    PURCH_AMT TEXT,
    ORDER_DATE TEXT,
    CUSTOMER_ID TEXT,
    SALESMAN_ID TEXT
);


INSERT INTO ORDERS(ORDER_NO, PURCH_AMT, ORDER_DATE, CUSTOMER_ID, SALESMAN_ID)
VALUES
("70001","150.5","2012-10-05","3005","5002"),
("70009","270.65","2012-09-10","3001","5001"),
("70002","65.26","2012-10-05","3002","5003"),
("70004","110.5","2012-08-17","3009","5007"),
("70007","948.5","2012-09-10","3005","5005"),
("70005","2400.6","2012-07-27","3007","5006");

-- CUSTOMER QUERYS PART 1
SELECT CUSTOMER.CUSTOMER_NAME, SALESMAN.SALESMAN_NAME, SALESMAN.CITY
FROM CUSTOMER
JOIN SALESMAN ON CUSTOMER.CITY = SALESMAN.CITY;

SELECT CUSTOMER.CUSTOMER_NAME, SALESMAN.SALESMAN_NAME
FROM CUSTOMER
JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID;


-- ORDERS QUERYS PART 1
SELECT ORDERS.ORDER_NO, CUSTOMER.CUSTOMER_NAME, ORDERS.CUSTOMER_ID, ORDERS.SALESMAN_ID
FROM ORDERS
JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
JOIN SALESMAN ON ORDERS.SALESMAN_ID = SALESMAN.SALESMAN_ID
WHERE CUSTOMER.CITY <> SALESMAN.CITY;

SELECT ORDERS.ORDER_NO, CUSTOMER.CUSTOMER_NAME
FROM ORDERS
JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;

SELECT CUSTOMER.CUSTOMER_NAME AS "CUSTOMER", CUSTOMER.GRADE AS "GRADE"
FROM ORDERS
JOIN SALESMAN ON ORDERS.SALESMAN_ID = SALESMAN.SALESMAN_ID
JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE CUSTOMER.GRADE IS NOT NULL;


-- CUSTOMER QUERYS PART 2
SELECT CUSTOMER.CUSTOMER_NAME AS "CUSTOMER",
CUSTOMER.CITY AS "CITY",
SALESMAN.SALESMAN_NAME AS "SALESMAN",
SALESMAN.COMISSION
FROM CUSTOMER
JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID
WHERE SALESMAN.COMISSION BETWEEN 0.12 AND 0.14;


-- ORDERS QUERYS PART 2
SELECT ORDERS.ORDER_NO, CUSTOMER.CUSTOMER_NAME, SALESMAN.COMISSION AS "COMISSIONS",
ORDERS.PURCH_AMT * SALESMAN.COMISSION AS "COMISSION"
FROM ORDERS
JOIN SALESMAN ON ORDERS.SALESMAN_ID = SALESMAN.SALESMAN_ID
JOIN CUSTOMER ON ORDERS.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE CUSTOMER.GRADE >= 200;



-- CUSTOMER QUERYS PART 3
SELECT *
FROM CUSTOMER
JOIN ORDERS ON CUSTOMER.CUSTOMER_ID = ORDERS.CUSTOMER_ID
WHERE ORDERS.ORDER_DATE = '2012-10-05';